/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WipEnvelopeRouteImport } from './routes/wip-envelope'
import { Route as EnvelopeRouteImport } from './routes/envelope'
import { Route as ContentRouteImport } from './routes/content'
import { Route as IndexRouteImport } from './routes/index'

const WipEnvelopeRoute = WipEnvelopeRouteImport.update({
  id: '/wip-envelope',
  path: '/wip-envelope',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvelopeRoute = EnvelopeRouteImport.update({
  id: '/envelope',
  path: '/envelope',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/envelope': typeof EnvelopeRoute
  '/wip-envelope': typeof WipEnvelopeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/envelope': typeof EnvelopeRoute
  '/wip-envelope': typeof WipEnvelopeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/envelope': typeof EnvelopeRoute
  '/wip-envelope': typeof WipEnvelopeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/content' | '/envelope' | '/wip-envelope'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/content' | '/envelope' | '/wip-envelope'
  id: '__root__' | '/' | '/content' | '/envelope' | '/wip-envelope'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRoute: typeof ContentRoute
  EnvelopeRoute: typeof EnvelopeRoute
  WipEnvelopeRoute: typeof WipEnvelopeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wip-envelope': {
      id: '/wip-envelope'
      path: '/wip-envelope'
      fullPath: '/wip-envelope'
      preLoaderRoute: typeof WipEnvelopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envelope': {
      id: '/envelope'
      path: '/envelope'
      fullPath: '/envelope'
      preLoaderRoute: typeof EnvelopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRoute: ContentRoute,
  EnvelopeRoute: EnvelopeRoute,
  WipEnvelopeRoute: WipEnvelopeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
